### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Carreau** [FlyBrainLab/FlyBrainLabWeb#1]
https://github.com/FlyBrainLab/FlyBrainLabWeb/blame/91369ad32f195550bd3e1cc1230ab1cf0a01e616/_posts/2000-01-07-video.md#L11 give a 404 on the website.

**Comment by mkturkcan** [comment]
Thanks! Fixed in 4c4ff5e49e15ddf7d9905e16f17089f5aa634550.
The link points to [https://github.com/FlyBrainLab/FBLClient/tree/master/examples/jupyter_notebooks](https://github.com/FlyBrainLab/FBLClient/tree/master/examples/jupyter_notebooks).
